### ISSUE TITLE
Problem connecting to the Nano board using an FTDI Cable 5V.

### ISSUE THREAD

**Issue by ReneElizondo** [sparkfun/Simultaneous_RFID_Tag_Reader#10]
Hello,

I have a **_SparkFun Simultaneous RFID Reader - M6E Nano_** that I interface with a [SparkFun Serial Basic Breakout - CH340G](https://www.sparkfun.com/products/14050) (setup to use 5 volts logic) and everything works perfectly fine. If I leave things exactly the same and I only replace the **_SparkFun Serial Basic Breakout - CH340G_** with a [FTDI Cable 5V](https://www.sparkfun.com/products/9718) things don’t work.

Why is that? Aren’t the **_SparkFun Serial Basic Breakout - CH340G_** and **_FTDI Cable 5V_** supposed to be functionally equivalent?

Note: 

*) The **_FTDI Cable 5V_** is recognized by the computer (using Windows) just fine (using the latest drivers) so there are no issues with drivers etc.

*) I have tested the **_FTDI Cable 5V_** cable by communicating with an Arduino board and the cable functions perfectly.

*) The **_FTDI Cable 5V_** cable still fails even if an external / independent 5 VCC power source is provided to the Nano (in this case the only pins used by the **_FTDI Cable 5V_** cable are just RX, TX and ground, the VCC in the cable is disconnected so I don't think the cable is failing due to not being able to provide enough power.

*) The cable fails while trying to do the basic initial handshake (the part where the 'Universal Reader Assistant' software tries to identify the Nano board), I don't even get to the point where I don any RFID reading.

The reason for me using the **_FTDI Cable 5V_**  cable is because I am having all kinds of issues (sporadic ones) connecting to the Nano board via serial. So in order try to diagnose the problem (with my limited skills) I decided to purchase the cable and see if things would work with that cable (just as an experiment). I figured such an experiment may shed some light as to why I am having all the serial connection issues.

I strongly suspect this is not a **_FTDI Cable 5V_** cable issue, my gut feeling tells me this is a Nano issue....

Thanks.

**Comment by nseidle** [comment]
Curious. Differences that come to mind: the CH340G has an external crystal where the FT232 uses an internal oscillator. We've seen some rare cases where the CH340C (internal oscillator) is just enough out of spec that it cannot communicate with an ATmega328 (external resonator) for bootloading (115200). Whether it is the CH340C that is off or the external resonator on the ATmega328 - I cannot say. Just know that clocks might be a thing. A [logic analyzer](https://www.sparkfun.com/products/18627) would tell you quickly enough if your serial timing is out of spec.

My last guess is that the FT232 needs to have its CTS pin pulled low. I don't know enough about how the IC is configured in the black blob of the FTDI cable to say if it has a pull down on the CTS pin. If it doesn't, or if it's pulled up, the FT232 won't do transmit until it's low.

**Comment by ReneElizondo** [comment]
Thanks Nathan,

A couple of things:

When I connect a logic analyzer (the exact one you mention, I actually purchased that device to troubleshoot exactly this issue) two things happen. When I plug the CH340G board, both the RX and TX lines are completely quiet, they are just high and stay high unless a command is issued the Nano. However, when I plug the FTDI Cable 5V, things get really noisy on the Nano TX pin, see screenshot below:

![BadTx](https://user-images.githubusercontent.com/88205225/147792211-f4c8d1f7-cd87-4b4f-b23e-79316ac2ffc6.png)

To be clear, that is what is going on on the Nano TX pin without me doing anything (right after connecting the cable to the Nano board), no commands are issued to the Nano board but the Nano board is essentially going nuts sending signals no one is asking for. Why would that be? If I then issue a command to the Nano via the 'Universal Reader Assistant' to detect the board I see the Nano RX line receiving the command but the Nano TX line continues to go nuts. The baud speeds are just fine, they are the same on both the CH340G and FTDI Cable 5V.

Regarding your CTS pin question, based on the [schematics](https://www.sparkfun.com/datasheets/DevTools/FTDI%20Cable%205V.pdf), the CTS pin appears to be pulled up, if you would like me to experiment by pulling the pin low I can do that but I would need to know exactly how to do that since I have very limited electronics knowledge and I don't want to burn something up. It may be also worth mentioning that the Nano board does not use the CTS pin (is not connected / NC) so I am not sure if the state of the pin matters or not.

Given that the FTDI Cable 5V cable works perfectly fine with an Arduino board, I still think that this is not an issue with the cable, I still believe this is an issue with the Nano serial circuitry being unstable under certain conditions (like long cables perhaps). I say this because trying to get the serial communication working with the Nano and a device such as a Raspberry Pi is very unstable.

Thanks.

**Comment by nseidle** [comment]
CTS: the FTDI pulls it up, CH340x board leaves it floating. I'm not sure why the Nano is sending so much TX noise. Sorry, but because of the holidays I won't have access to hardware to replicate your issue until late next week.

**Comment by ReneElizondo** [comment]
Nathan,

Not sure if you are still looking into this but in case you are. The screenshot below shows the oscilloscope signal coming directly from a Raspberry Pi TX pin (3V). Note that the pin is not connected to the Nano board, its just floating, but I also connected the pin to resistor and got the same result. Its a relatively nice clean signal.

![DS1Z_QuickPrint2](https://user-images.githubusercontent.com/88205225/149640685-7708e0ca-d40d-446f-ab96-eb9a86a0ab1e.png)

The screenshot below shows the oscilloscope signal coming directly from the same Raspberry Pi TX pin (3V) but this time, the TX pin is connected to the Nano RX pin:

![DS1Z_QuickPrint1](https://user-images.githubusercontent.com/88205225/149640715-9f5616fd-e392-4a8b-8707-fbbad2d5ca23.png)

You can see all the noise introduced by the Nano. I get similar results if I use a level shifter. Why the noise? Does this not mean there is something up with the Nano design?

Thanks.

**Comment by ReneElizondo** [comment]
Looks like even the Serial Basic Breakout - CH340G signal goes nuts when I plug in the oscilloscope. The Nano will stop working if all I do is plug the oscilloscope to the RX or TX pin. The moment I unplug the oscilloscope the Nano goes back to working. Not sure what is going on but looks like the Nano board has some issues. 

![DS1Z_QuickPrint3](https://user-images.githubusercontent.com/88205225/149643236-1bb15a0f-669e-4de1-a3bd-d662e1522bde.png)

**Comment by nseidle** [comment]
I don't have answers, only head scratching.

* CH340E and CH340G connect to the M6E (you call it the Nano) great when direct to the port on my computer, but fail when used through a hub. 
* The [FTDI 5V with 5V IO](https://www.sparkfun.com/products/9718) enumerates on my computer but cannot connect to the M6E. And fails even to enumerate through the hub.

Looking at serial signals, I am seeing similar noise at the TXO pin on the M6E board, sometimes. My current guess is that the M6E internal DC buck/boost is feeding noise back into the TXB0104 digital buffer causing it to spew bad serial. I detached the TXB0104 from the 3.3V coming from the M6E and fed it a separate 3.3V but that did not allow the FTDI to connect.

I'll check with our tech support team to see if they've seen or heard anything similar.

**Comment by ReneElizondo** [comment]
These readers (from jadaktech) have issues enumerating through USB. In case it help, I created the following thread on the Pi forums some time ago:

https://forums.raspberrypi.com/viewtopic.php?t=320242

I also contacted jadaktech and months later still no answer as to why the USB issues. They were able to replicate the problem but have not come up with a resolution... and for the looks of it, I doubt the issue will ever get fixed unless they get to the point that they decide to revamp or create a new chip.

**Comment by paulvha** [comment]
ReneElizondo pointed me to this posting as we had contact about this on the Sparkfun forum before and I have done a lot of work on the RFID reader. This is an interesting challenge/issue and decided to put some time into analyzing

Forgive me for the long answer, but long story short: I think that I know the root cause: too low line RX line-level caused by the resistor bridge in the FTDI cable. Given the long answer, I will start the conclusions followed by the supporting test results for FYI

I have tested 3 different conditions: Cable FTDI, CH340G, and Adafruit FTDI FRIEND. 

Every time the **same setup** : 
M6E TX connected to 5K6 pull-down & logic analyser only. Not connected to FTDI- RX
M6E RX connected to FTDI / Ch340 or FRIEND TX-output & logic analyser.

**My conclusion**
The issue is NOT coming from the power supply line itself. The 3V3 and VCC are (nearly) rock solid the whole time. The BIG difference and the root cause in my mind  is the level on the M6E-RX line-level: with the cable FTDI it is around 50% the level which it is with the CH340 and the FRIEND in between :

```
CH340    FTDI     FRIEND M6E RX-LINE level
4.804V    2.882V  3.058V   BEFORE sending connect
4.798V    2.3V   3.058V    DURING sending connect
4.804V    2.276V  3.06V      AFTER  sending connected
```
These cable FTDI values on the M6E RX line can cause the M6E to detect a zero, causing the board/M6E to go crazy. The low level would also explain that when connecting a scope, it can impact the line-level a little bit.. just enough to cause incorrect line reading by the M6E. Also when using a HUB the provided VCC might already be lower causing an even lower FTDI-TX signal.

```
CH340    FTDI     FRIEND  M6E TX-line (connected to 5k6 resistor)
2.797V    2.515V  2.516V    BEFORE sending connect 
2.805V    2.8V      2.805V    DURING sending connect  (cable FTDI starting jitter)
2.795V    2.837V  2.515       AFTER sending connect (Cable FTDI Jittering)
```

The TX line values are nearly the same across the 3 converters. 

Looking at the schematics I see there is a resistor/divider on the Cable FTDI TX: 10K to VCC and 100 ohm to the chip. I suspect that is causing the issue of a too low line level in combination with the TXB0104 on the M6E board. The CH340G does NOT have resistors and the FRIEND has 10 OHM protection serial on its TX.

Why does this cable then work with other devices? I suspect a combination with TXB0104. 

When I tried to use a Sparkfun logic Level Converter (BOB-12009) 2 years ago with an ESP32, the RFID reader would fail as well. The level converter also has a 10K pull-up. After removing the level converter then applying a resistor divider on M6E-TX line to level down the 5V to 3V3 and connecting the M6E-RX directly to the ESP32 it all worked without problems.

Regards,
Paul

**Connected FTDI cable to Windows PC**
Before sending the connect (asking for firmware/hardware level) 
VCC stable constant 4.217V. 
3v3 stable constant 3.7V.
M6E - RX line level 2.882V.
M6E- TX line at 2.515V.

During sending a connect command from the URA :
VCC stable constant 4.192V. 
3v3 stable constant 3.713V.
On FTDI-TX / M6E-RX, the HIGH (1)  is 2.3V.  At the same time are HIGH on the M6E-TX around 2.8V  (UP from before) and starting to jitter. This jitter does NOT come from the FTDI-RX (as it is not connected). The TX line continues to jitter from then on.

After sending the request 
VCC stable constant 4.185V. 
3v3 stable constant 3.7V.
M6E - RX line level around 2.276V.
M6E- TX line at 2.837V.
![FTDI_CONNECT](https://user-images.githubusercontent.com/16015548/150318413-bc31d6fe-da15-407f-9097-6c82e30c73f1.png)

**Connected CH340 to Windows PC**

Before sending the connect (asking for firmware/hardware level) 
VCC stable constant 4.745V. 
3v3 stable constant 3.594V.
M6E - RX line level 4.804V.
M6E- TX line at 2.797V.

During sending a connect command from the URA :
VCC stable constant 4.742V. 
3v3 stable constant 3.596V.
On FTDI-TX / M6E-RX, the HIGH (1)  is 4.798V.  The M6E TX line rock stable at 2.805V. 
After the M6E received the command it responds with the right data, with a HIGH (1) being at
2.795V.

After sending the request to M6E and receiving the data :
VCC stable constant 4.746V. 
3v3 stable constant 3.597V.
M6E - RX line-level 4.804V.
M6E - TX line at 2.795V.

![CH340-connect](https://user-images.githubusercontent.com/16015548/150318550-40f2a688-36e6-4ccb-929c-015a088cd139.png)

**Connect FTDI Friend to windows PC**

Before sending the connect (asking for firmware/hardware level) 
VCC stable constant 4.389V. 
3v3 stable constant 3.605V.
M6E - RX line level 3.058V.
M6E- TX line at 2.516V.

During sending a connect command from the URA :
VCC stable constant 4.389V. 
3v3 stable constant 3.605V.
On FTDI-TX / M6E-RX, the HIGH (1)  is 3.058V.  The M6E TX line rock stable at 2.805V. 
After the M6E received the command it responds with the right data, with a HIGH (1) being at
2.514V.

After sending the request to M6E and receiving the data :
VCC stable constant 4.391V. 
3v3 stable constant 3.605V.
M6E - RX line-level 3.06V.
M6E - TX line at 2.515V.
![FRIEND-connect](https://user-images.githubusercontent.com/16015548/150318711-6a9f924a-d23d-4185-89a8-5cec22c9917f.png)

**Comment by nseidle** [comment]
@paulvha - I am greatly appreciative for the deep dive.

I have updated the product page and hookup guide to warn users away from using the FTDI cable.

**Comment by ReneElizondo** [comment]
@nseidle: Just out of curiosity, what about the other issues? Like all the noise that is generated when trying to interface the RFID reader with a Raspberry Pi etc. Will you guys look into that issue to see if it can be resolved?

**Comment by paulvha** [comment]
How did you connect the RFID to the Raspberry Pi? I could try to replicate that over the weekend. 

Earlier I programmed the RFID with MercuryAPI and connected it using to the USB interface. Never had a problem (CH340G).

regards,
Paul

**Comment by ReneElizondo** [comment]
I connected the Raspberry Pi TX pin to the M6E RX pin directly (3V logic), I also tried two different level shifters (BOB-12009 and BOB-11771) between the Pi and the M6E and got the same noise. Pretty much what I described in the previous post: https://github.com/sparkfun/Simultaneous_RFID_Tag_Reader/issues/10#issuecomment-1013770345

I own two M6E readers and the two are having the same issue. Hope you have the time and can replicate, perhaps I am doing something wrong. Look forwards to hearing your results.

**Comment by paulvha** [comment]
Thanks,

Can you share the exact RPI-pin to RFID-pin connections  (also VCC)
What program did you use to test?

regards,
Paul

**Comment by ReneElizondo** [comment]
My apologies for the long delay, something urgent came up and I got side tracked.

To answer your question. From the RPI side I have the following setup:

*) 5 Volts from physical pin 4.
*) Ground from physical pin 6.
*) TX from physical pin 8.

From the M6E side:

*) 5 Volts to FTDI connector pin labeled VCC.
*) Ground to FTDI connector pin labeled GND.
*) TX (from RPI) to FTDI connector pin labeled RXI.

The program I used to test this is a custom .NET Core / C# app that basically attempts to open a connection to the M6E and read a tag. If you want it I can upload it but its pretty big since it needs to have all the .NET Core runtime. My guess is that any serial signal sent from any app will cause the same issue.

![PIM6E](https://user-images.githubusercontent.com/88205225/150618437-24647eb8-bfd5-4517-8f26-c18f360d6541.jpg)

The output on the oscilloscope looks like this in my side:

![DS1Z_QuickPrint1](https://user-images.githubusercontent.com/88205225/150618555-4918d353-1b10-4d7f-81b8-854c4a94f85e.png)

Look forward from learning about your findings!

**Comment by paulvha** [comment]
I connected to my RPI- 4 in the same way as you did. I have also connected the M6E-TX to either 5K6 OR pin 10 (UART0-RX). 

Connected the logic analyzer to RX, TX, GND, and 5V. As I did not have the program, I used a simple Python program testserial.py:

```
#!/usr/bin/env python

import time
import serial

ser = serial.Serial(
    port='/dev/serial0',
    baudrate = 115200,
    parity=serial.PARITY_NONE,
    stopbits=serial.STOPBITS_ONE,
    bytesize=serial.EIGHTBITS,
    timeout=1
)

while 1:
    ser.write('\xff')
    ser.write('\x00')
    ser.write('\x03')
    ser.write('\x1d')
    ser.write('\x0C')
    
    time.sleep(1)
```
You can run this from a terminal with the command:  python testserial.py

It worked without a problem, (P.s. I have not connected the 3V3 so it shows zero) : 
![RPI2_connect](https://user-images.githubusercontent.com/16015548/150648638-67fd035d-32a9-4e38-8d0c-decb8b31ec75.png)


I have tried to remove the power and reconnect the 5V while the RPI was powered: NO difference.
I have tried to remove the RX-line and reconnect while the RPI was powered: NO difference.
I have tried to remove the TX-line and reconnect while the RPI was powered: NO difference.
I have tried to remove the RX-LINE  & TX-line and reconnect while the RPI was powered: NO difference.

Looked at the picture of your scope:
1. Is the scope probe set to 10X ( that will decrease the impact the scope probe has on the circuit)
2. connect the M6E TX  to the UART0 RX to create a resistor load
3. check the 5V with another scope probe at the same time. Some 5V wall suppliers deliver a too low current

regards,
Paul

**Comment by ReneElizondo** [comment]
Thanks Paul,

You where absolutely correct regarding the prove setting, I had it at 1X and after I changed it to 10X the signal looked a lot better:

![DS1Z_QuickPrint2](https://user-images.githubusercontent.com/88205225/150654346-7419d549-f3c3-4d3e-8f45-c2204198f50d.png)

There is still some ringing in the signal but I assume that is just an oscilloscope artifact:

![DS1Z_QuickPrint3](https://user-images.githubusercontent.com/88205225/150655170-b9b496d3-6cd2-4949-8d1f-4bd6bf8e3b6b.png)

This is puzzling, I am still not sure why I can't get the M6E to work consistently reliably with the Pi. I will continue to explore and see if I can figure out what the problem is.

If you don't mind I have a quick question for you. In theory, if I feed a 5 volt signal to the M6E RX pin, the 5V signal would get translated to 3.3 V via the built in TXB0104 chip. The question is, what happens if instead of feeding a 5V signal to the M6E RX pin I feed a 3.3V signal? What would the TXB0104 chip do? Would it output 3.3V on the low voltage side because that is as low as its supposed to go? Or would it interpolate the value and output a much lower signal like say 1.5V?

Sorry for the dumb question, I can try this that myself (and I will) but I am curious as to what the expected result should be so I know what to look for (just so I can double check myself).

Thanks.

**Comment by paulvha** [comment]
Good it works now much better. 

The "ringing" is often the result of the capacitive impact of either or combination of the wires, the connections,  the scope, the logic (either Raspberry or M6E). 

As it relates to your TXB0104 question, it **translates** the M6E-RX line level on the VVC-A side to the output level of VCC-B. It detects a "1" compared to the VCC-A level and then outputs a "1" based on VCC-B level. (VVC-A = 5V, VCC-B = 3V3)  It is NOT stepping down the input signal.

For the M6E-TX it does the opposite translation. The M6E-TX output will be to the level of VCC-A. As you see on my post that shows ~4.2V. This can be TOO high for the Raspberry (max should be 3V3) causing misreadings and/or damage. So include a resistor based level shifter on the M6E-TX line ONLY :  

```
GND ------| 10K  |-----!---- | 5k6 |------  TX from Nano
                       !   
                       !
                  Pin 8 ( UAR0-RX)
```
Normally I use the M6E on Raspberry Pi with the USB connection.

Regards,
Paul
