### ISSUE TITLE
ERROR_COMMAND_RESPONSE_TIMEOUT

### ISSUE THREAD

**Issue by robertshearing** [sparkfun/Simultaneous_RFID_Tag_Reader#3]
Hi,
I'm trying to get this code working but I cannot get the board to start. 
I've found that when the call to getVersion:
`nano.getVersion();`
is called I get a 1 returned (ERROR_COMMAND_RESPONSE_TIMEOUT)

I have the board working using the thing magic Universal reader Assistant and I'm powering the Arduino (Leonardo) with an external 5v power source. I have checked that all the required pins (gnd, 5v, D2, D3, D9, D10) are all good connections and it is switched to SW_UART. The power light is on and I can get the buzzer to sound.

Are you aware of this problem happening and is there a way I can diagnose it further or fix it?

Thanks,
Rob

**Comment by nseidle** [comment]
Hi Rob,

My initial guess is that the serial from the Leonardo is not getting past the conversion circuitry. The TXB0104 in [the schematic](https://cdn.sparkfun.com/datasheets/Sensors/ID/Simultaneous_RFID_Tag_Reader.pdf) requires that VCC going into the board be larger than 3.3V.  But the Leonardo should be providing 5V to the board so I don't think that's the culprit...

Does Leonardo handle software serial correctly? Ok, looks like only a [handful of pins](https://www.arduino.cc/en/Reference/SoftwareSerial) can be used on Leonardo for software serial, but 9 and 10 can both be used for RX so that seems to not be the culprit.

Is the Leonardo pulling down the Enable pin on ... nope, not connected.

Do you have a [logic analyzer](https://www.sparkfun.com/products/13195)? It would help verify if serial is getting from Leonardo through TXB0104 to the RFID module. Ah, or here's an idea: you have a USB-to-Serial adapter so if you connect only GND and the RXI pin on the 6-pin serial connection to your USB-to-Serial adapter you should be able to inspect via a terminal what the Leonardo is sending to the module.

Sorry I don't have a smoking gun for you yet. Please let me know what you find.

**Comment by robertshearing** [comment]
Hi Nate,

Thanks for getting back to me on this one so quickly.
It turns out that Leonardo (and Mega) can't use pins 2 and 3 for the Software Serial library: https://www.arduino.cc/en/Reference/softwareSerial

So I just wired it up differently to use pins 9 and 10 for the Rx Tx and it worked immediately!
I have now just switched over the buzzer pins and the SW-UART pins with jumper wires.

It might be good to add this in somewhere in the user guide incase other people have the same issue.

Thanks again for helping out,
Rob

**Comment by nseidle** [comment]
Why did I think the Software TX/RX were on pins 9/10? Excellent! Glad you got it working. 

FYI - The software serial limitation only applies to RX pins (because the library needs a change interrupt). You should only need to move D2 to something else (TX from RFID into RX on pin 2 on Leonardo).

**Comment by nseidle** [comment]
Notes added on [hardware page](https://learn.sparkfun.com/tutorials/simultaneous-rfid-tag-reader-hookup-guide/hardware-hookup) and [example 1](https://learn.sparkfun.com/tutorials/simultaneous-rfid-tag-reader-hookup-guide/example-1---constant-read).
